### PR TITLE
include quan-trunk as git submodule

### PR DESCRIPTION
**Pull request by xythobuz**
If the user does not initialize the submodule properly, `make` will print an error message.

### CODE REVIEW

**Comment by kwikius** [comment]
This is good in theory, but submodules always seem to cause me confusion. So I will have to think some more about this

**Comment by xythobuz** [comment]
Sure, No problem.

It was just a bit confusing for me, because it isn't really mentioned anywhere that you need quan-trunk and where to put it. So I thought this will make it easier for the casual user, he can now just type make and is told what he needs to do, without having to care for the quan-trunk dependency.

**Comment by kwikius** [comment]
OK noted. For now I think  I would prefer to add some docs about how to invoke either with the QUAN_INCLUDE_PATH on cmd line or exported , maybe remove the hardwired dir path for QUAN_INCLUDE_PATH from the Makefile and check the QUAN_INCLUDE_PATH is valid and  if not issue a diagnostic.

**Comment by kwikius** [comment]
@xythobuz 
I modified the Makefile to provide a diagnostic. I guess I should really do some docs

**Pull request closed without merging**
